### ISSUE TITLE
e= fails to detect unequality

### ISSUE THREAD

**Issue by Velrok** [mikera/vectorz-clj#2]
I stumbled upon this behavior:

`e=` seams failing to detect if two matrices are NOT equal, while the std `=` function does.

Is this indeed a bug or am I wrong about my assumptions?

``` clojure
(ns athena.math-lib-assumptions-spec
  (:use [speclj.core]
        [clojure.core.matrix]
        [clojure.core.matrix.operators]))

(set-current-implementation :vectorz)


(describe "e="
  (with expected (matrix [[1 2]
                          [3 4]]))

  (it "detects equality"
    (should (e= @expected
                (matrix [[1 2]
                         [3 4]]))))
  (it "FAILS TO DETECTS UNEQUALITY DONT USE IT"
    (should (e= (matrix @expected)
                (matrix [[2 2]
                         [3 4]])))))


(describe "= for matrices"
  (with expected (matrix [[1 2]
                          [3 4]]))

  (it "detects equality"
    (should= @expected
              (matrix [[1 2]
                       [3 4]])))
  (it "detects unequality"
    (should-not= (matrix @expected)
                 (matrix [[2 2]
                          [3 4]]))))
```

**Comment by mikera** [comment]
Yes this is a bug - thanks for finding it!

It's actually a bug in core.matrix, not vectorz-clj. Fixed in the latest core.matrix develop branch

In the meantime, `equals` should work (and is usually better, since it does proper numeric equality rather than java.lang.Object.equals comparisons - which causes problems because `(long 1)` does not e= `(double 1)` )

**Comment by Velrok** [comment]
Thanks for the fast answer!

I did know about the difference, since its explicitly state in `(doc e=)` and it also referes one to `e==`.

Just for the record the current development hash is 3d1ac62428f66aadc26d55d85ff99bab3dbca17d.
