### ISSUE TITLE
set-nd on matrix returns nil

### ISSUE THREAD

**Issue by mschuene** [mikera/vectorz-clj#20]
(mp/set-nd (matrix :vectorz [[1 2][3 4]]) [0 1] 3) => nil
Should fallback to calling its set-2d implementation
Come up in the mailing list https://groups.google.com/forum/#!topic/numerical-clojure/FsXo5j83hSM

**Comment by mikera** [comment]
I have a fix for this in my tree, will push out soon

**Comment by mikera** [comment]
Fixed in 0.22.0
