### ISSUE TITLE
project.clj version ahead of pom.xml

### ISSUE THREAD

**Issue by mars0i** [mikera/vectorz-clj#25]
In the develop branch, pom.xml says the version is 0.22.1-SNAPSHOT, while project.clj has 0.23.1-SNAPSHOT.  I'm guessing that project.clj is wrong (did I do that?), since 0.22.0 is the latest release.  Almost doesn't seem worth mentioning, but might as well.

**Comment by mikera** [comment]
I might have done that by accident when I updated the dependencies. Fixed now, thanks!
