### ISSUE TITLE
Bug in Cholesky

### ISSUE THREAD

**Issue by mikera** [mikera/vectorz-clj#29]
Cholesky decomposition seems to produce odd results where it should return nil, e.g.:

``` clojure
(cholesky (matrix :vectorz [[1 2] [2 1]]))
=> {:L* #<Matrix22 [[1.0,2.0],[0.0,NaN]]>, :L #<Matrix22 [[1.0,0.0],[2.0,NaN]]>}
```

**Comment by mikera** [comment]
@prasant94 one for you to take a look at? I think this should be returning nil whenever the matrix is not positive semi-definite

**Comment by prasant94** [comment]
yes, I am aware of this. We are still using the `SimpleCholesky` implementation in vectorz. This should go away once we switch to the new implementation.

**Comment by mikera** [comment]
OK cool. Good to switch over as soon as we can, I think? Or modify the SimpleCholesky to be smarter and detect these cases?

**Comment by prasant94** [comment]
This has been done. Closing it
