### ISSUE TITLE
Inconsistency with QR results

### ISSUE THREAD

**Issue by mikera** [mikera/vectorz-clj#31]
The default implementation and vectorz-clj implementations of QR decomposition produce quite different shapes of result for rectangular matrices:

With Clojure persistent vectors:

``` clojure
(qr [[1 2] [3 4] [5 6] [7 8]])
  {:R [[-9.165151389911681 -10.910894511799619] 
       [0 -0.975900072948533] 
       [0 0] 
       [0 0]], 
    :Q [[-0.10910894511799607 -0.8295150620062532 -0.3945010222838296 -0.3799591338775966] 
        [-0.32732683535398854 -0.4391550328268402 0.24279654570435638 0.800655879510063] 
        [-0.5455447255899809 -0.04879500364742667 0.6979099754427761 -0.46143435738733596] 
        [-0.7637626158259733 0.34156502553198664 -0.5462054988633029 0.040737611754869674]]}
```

With `vectorz-clj`:

``` clojure
(qr (matrix :vectorz [[1 2] [3 4] [5 6] [7 8]]))
{:R #<Matrix [[-9.16515138991168,-10.91089451179962],
              [0.0,-0.9759000729485332]]>, 
 :Q #<Matrix [[-0.10910894511799629,-0.8295150620062537],
              [-0.3273268353539886,-0.43915503282683965],
              [-0.545544725589981,-0.048795003647426116],
              [-0.7637626158259734,0.3415650255319861]]>}
```

I think the API should specify what shape of result should be returned, or if there is a choice of result format these should be specified through the decomposition options.

**Comment by prasant94** [comment]
vectorz-clj seems to be returning the compact version of R

**Comment by mikera** [comment]
Yes.... do you think that is the best approach?

**Comment by mikera** [comment]
@Gerrrr what do you think from the Incanter perspective?

**Comment by prasant94** [comment]
No, I think it should return the whole thing unless the user asks for the compact one specifically. We can then add that option later.

**Comment by mikera** [comment]
So that means Q will always be square and orthogonal by default? I'm OK with that, seems to make sense. `:compact true` probably should be an option then.

**Comment by Gerrrr** [comment]
In Incanter there is no way to specify compact or full version. It always returns full version like in default implementation.
I agree that providing `:compact true` option is a good solution.

**Comment by mikera** [comment]
@Preasant94 is this fixed now? Should we close?

**Comment by prasant94** [comment]
Not yet, I'll do this ASAP.

**Comment by prasant94** [comment]
I already did this.
Sorry, I got confused because I was on another old branch and I couldn't find the code so I thought I didn't do it.
