### ISSUE TITLE
Exponential with matrices

### ISSUE THREAD

**Issue by marthall** [mikera/vectorz-clj#49]
Would it be possible to add support for doing exponential with matrices.

In python numpy, it is possible to do

``` python
$ A = np.array([[1,2],[3,4]])
$ 2 ** A
array([[ 2,  4],
       [ 8, 16]])

# as well as
$ A ** 2
array([[ 1,  4],
       [ 9, 16]])
```

This would be super-useful in more complex equations. I'm looking forward to hear from you!

**Comment by mikera** [comment]
I think this works already if you do something like the following:

``` clojure
(pow 2 (array :vectorz [[1 2] [3 4]]))
=> #object[mikera.matrixx.Matrix 0x70bdd4da "[[2.0,4.0],\n[8.0,16.0]]"]
```

Does that solve your issue?

**Comment by marthall** [comment]
Oh, that's awesome! I tried with `(expt 2 (array :vectorz [[1 2] [3 4]]))` where `expt` is from `clojure.math.numeric-tower`. Stupid of me :smile: 

This will solve my problem. Thank you so much for this awesome library!
