### ISSUE TITLE
The inverse function in combination with the diagonal-matrix function seems to be bugged

### ISSUE THREAD

**Issue by wilfreddenton** [mikera/vectorz-clj#54]
If I run
`(inverse (matrix [[1 0] [0 2]]))`
I get
`#vectorz/matrix [[1.0,-0.0],[-0.0,0.5]]`

However when I run
`(inverse (diagonal-matrix [1 2]))`
I get
`#vectorz/matrix [[Infinity,0.0],[0.0,Infinity]]`

Not sure what is going on here because the output of both
`(matrix [[1 0] [0 2]])` and `(diagonal-matrix [1 2])` is `#vectorz/matrix [[1.0,0.0],[0.0,2.0]]`

**Comment by mikera** [comment]
Thanks I just confirmed this was an issue with the underlying Vectorz library. I have a fix in the latest develop branch, let me know if you want a new release.

Workaround right now is to use `clone` first: 

``` clojure
(inverse (clone (diagonal-matrix [1 2])))
=> [[1.0 -0.0] [-0.0 0.5]]
```

**Comment by wilfreddenton** [comment]
I'll use the workaround for now. Thanks!

**Comment by wilfreddenton** [comment]
Actually I just the workaround and it isn't working for me either.

**Comment by mikera** [comment]
What do you get? Same issue using clone?

**Comment by wilfreddenton** [comment]
Yeah the issue using clone.

**Comment by mikera** [comment]
Now fixed in latest develop branch, will do a new release soon
