### ISSUE TITLE
Array creation on double array ~40x slower via core.matrix than when Vectorz/toVector used directly.

### ISSUE THREAD

**Issue by michaelochurch** [mikera/vectorz-clj#6]
Here's a REPL transcript on the case of a 20-million long vector. 
.
user> (def da (double-array (range 2e7)))
# 'user/da

;; 42 msec with direct call to Vectorz/toVector (Java API)
user> (time (def q (Vectorz/toVector da)))
"Elapsed time: 41.962 msecs"
# 'user/q

user> (time (def q (clojure.core.matrix/array da)))
Call to clojure.core.matrix.protocols/convert-to-nested-vectors took 1440.429 msec.
Call to mikera.vectorz.matrix-api/vectorz-coerce\* took 1726.304 msec.
"Elapsed time: 1726.534 msecs"
# 'user/q

Most of the time seems to be spent converting the array into nested vectors (and, presumably, the rest is spent converting it back). 

How easy or hard would it be to adapt this to avoid the round-trip in data types when a native double[](also, double[][] and higher dimensions) is passed in? It seems like this might require gut-level work on core.matrix in addition to vectorz-clj, but IMO it would be quite valuable to have fast vector/array creation when one already has a primitive double array. (I know those aren't Clojure idiomatic, but I find myself using them a lot for high-performance purposes.)

**Comment by mikera** [comment]
Good spot! Yes we should definitely fix this. 

I think the right strategy is for vectorz-clj to use the `clojure.core.matrix.protocols/to-double-array` protocol: this way any source implementation can provide an efficient conversion to a double[] array (for actual double[] arrays, this can just be an array clone). Then this can be converted directly into Vectorz format with Vector/wrap.

That way we only allocate one new double[] array, and the source implementation gets to determine the most efficient way of loading its elements into that double array via the protocol. Does that make sense?

**Comment by michaelochurch** [comment]
This makes sense. So is the best way forward for all of the Vector classes to implement that protocol?

Also, I see that this would make to-double-array conversions speedier, but does it also improve the performance of the core.matrix array? Or will calling Vector/wrap always be more performant?

**Comment by michaelochurch** [comment]
Never mind, I see what you're saying. I'll submit a PR soon. 

Performance is now at 2x (presumably due to the copying) instead of 40x. Can you think of any good way to improve on that?

**Comment by michaelochurch** [comment]
Ok, I sent a PR that fixes it. It was a one-line fix. 

It doesn't do anything for the two-dimensional (or N-dimensional case) but right now double[][] and higher are not even supported (there are no core.matrix implementations for them). Is that by design or would that be a worthy target?

**Comment by mikera** [comment]
Fix looks good! 

One slight additional change would be to use Vector/wrap which should get us to 1x performance by removing an unnecessary level of defensive copying. I added a comment to this effect to the PR.

Perhaps should also have a test case that confirms that a new copy has been made?

**Comment by mikera** [comment]
Regarding double[][], I think this would be a good implementation to support in `core.matrix` if anyone is inclined to write it - issue placeholder is here: https://github.com/mikera/core.matrix/issues/21

Not sure if higher dimensional arrays of doubles have so much value: in fact I'm not sure if there is a way to support these with Clojure protocols in a general way?

Note tht it is also possible to use Object[] arrays that contain double[] arrays to emulate a 2D mutable matrix. This should work already.

**Comment by mikera** [comment]
Closing this as it seems to be complete now. 

FWIW: I extended the default protocols in the latest core.matrix release (0.17.0) to support arbitrary nested Java arrays. Almost certainly not optimal performance yet, but at least it works. This does not prevent faster specific implementations, e.g. for `double[][]`
