### ISSUE TITLE
set-indices returns nil

### ISSUE THREAD

**Issue by juskrey** [mikera/vectorz-clj#62]
Using [net.mikera/vectorz-clj "0.45.0"]
```clojure
(set-indices (matrix [[1 1] [2 2]]) [[1 1]] [9])
=> [[1 1] [2 9]]
(set-indices (matrix :vectorz [[1 1] [2 2]]) [[1 1]] [9])
=> nil
```

**Comment by mikera** [comment]
Fixed in master, will be included in next release, hopefully soon.

Thanks for the report!

**Comment by mikera** [comment]
BTW this is not a very optimised operation. If you care about performance, other approaches will probably be better.

**Comment by juskrey** [comment]
Thank you!
