### ISSUE TITLE
function nth not supported

### ISSUE THREAD

**Issue by keesterbrugge** [mikera/vectorz-clj#69]
Hi, 

Awesome library. I think I found a bug however. 

Neither type `Matrix` nor `Vector` seem to support the function `nth`. This has the result that the type needs to be converted – e.g. using `to-nested-vectors` – before destructuring can be used.

Examples:
```clojure 
(nth (m/array [1 1]) 0)
```
and 
```clojure
(let [[x y] (m/matrix [2 2])]
    x)
```
both return the error message
```
Exception while evaluating the expression.
#unrepl/browsable
  [#error {:via [{:type java.lang.UnsupportedOperationException,
                  :message "nth not supported on this type: Vector",
                  :at [clojure.lang.RT nthFrom "RT.java" 928]}],
           :trace [[clojure.lang.RT nthFrom "RT.java" 928]
                   [clojure.lang.RT nth "RT.java" 893]
                   [user$eval34322 invokeStatic "NO_SOURCE_PATH" 1]
                   [user$eval34322 invoke "NO_SOURCE_PATH" 1]
                   [clojure.lang.Compiler eval "Compiler.java" 7176]
                   [clojure.lang.Compiler eval "Compiler.java" 7131]
                   [clojure.core$eval invokeStatic "core.clj" 3214]
                   [clojure.core$eval invoke "core.clj" 3210]
                   [user$eval34315 invokeStatic "NO_SOURCE_PATH" 52]
                   [user$eval34315 invoke "NO_SOURCE_PATH" 52] /117],
           :cause "nth not supported on this type: Vector"}
   /118]
``` 
Is this intended?

Cheers

**Comment by mikera** [comment]
Yes, it is intended. `nth` is a Clojure function that can't support arbitrary array types (it only supports a small number of fixed types / interfaces), so its use is discouraged with core.matrix implementations as this would make user code dependent on a specific implementation.

You should normally use `core.matrix` functions `mget` or `slice` instead, depending on whether you want a single element or a slice of the array. These functions use the `core.matrix` protocols to dispatch to the correct accessor methods.

Hope that helps!
