### ISSUE TITLE
Worthwhile to add a project.clj?

### ISSUE THREAD

**Issue by michaelochurch** [mikera/vectorz-clj#7]
I'd like to add a project.clj file so I can run the REPL and explore the code (as I look to modify it as discussed in the other issue). Would this be worthwhile, or would it conflict with other demands on the project?

If this isn't a good idea, then what is the recommended way to run a REPL against the code? (I don't know Maven very well.)

**Comment by mikera** [comment]
You are very welcome to add a project.clj, it works quite happily alongside Maven. 

The only challenge is that it may need occasional extra patching to update the dependency versions (since the Maven release plugin won't do this automatically, and humans have a tendency to forget :-) )
